window.TW24_PRODUCTS = {
  capabilities: [
    {
      id: "cap-20",
      number: 20,
      name: "Identity Protection",
      blurb: "Identity protection and account takeover prevention.",
      features: ["MFA Enforcement", "Credential Monitoring", "Behavioral Analytics"],
      price: 15,
      category: "Capability",
    },
    {
      id: "cap-1",
      number: 1,
      name: "Phishing Defense",
      blurb: "Phishing and social engineering defense.",
      features: ["AI Link Scanning", "Simulated Attacks", "Header Analysis"],
      price: 12,
      category: "Capability",
    },
    {
      id: "cap-18",
      number: 18,
      name: "Endpoint Threat Prevention",
      blurb: "Endpoint threat prevention.",
      features: ["NGAV", "Exploit Prevention", "USB Device Control"],
      price: 18,
      category: "Capability",
    },
    {
      id: "cap-4",
      number: 4,
      name: "Collaboration Security",
      blurb: "Email and collaboration security.",
      features: ["Slack Protection", "Teams Scanning", "SharePoint Defense"],
      price: 20,
      category: "Capability",
    },
    {
      id: "cap-13",
      number: 13,
      name: "Ransomware Protection",
      blurb: "Ransomware and malware protection.",
      features: ["Rollback Protection", "Behavior Blocking", "Offline Scanning"],
      price: 22,
      category: "Capability",
    },
    {
      id: "cap-6",
      number: 6,
      name: "Zero-Day Detection",
      blurb: "Zero-day and advanced threat detection.",
      features: ["Sandboxing", "Heuristic Analysis", "Static AI"],
      price: 25,
      category: "Capability",
    },
    {
      id: "cap-10",
      number: 10,
      name: "Cloud Protection",
      blurb: "Cloud and SaaS application protection.",
      features: ["CASB", "Cloud Posture", "Workload Protection"],
      price: 20,
      category: "Capability",
    },
    {
      id: "cap-15",
      number: 15,
      name: "Data Loss Prevention",
      blurb: "Data loss prevention.",
      features: ["Sensitive Data Discovery", "Exfiltration Blocking", "Compliance Patterns"],
      price: 18,
      category: "Capability",
    },
    {
      id: "cap-2",
      number: 2,
      name: "Insider Threat Monitoring",
      blurb: "Insider threat monitoring.",
      features: ["User Behavior Analytics", "File Access Logs", "Data Movement Tracking"],
      price: 15,
      category: "Capability",
    },
    {
      id: "cap-17",
      number: 17,
      name: "Secure Remote Access",
      blurb: "Secure access for remote and hybrid workers.",
      features: ["Zero Trust Network Access", "VPN Alternative", "Device Health Check"],
      price: 12,
      category: "Capability",
    },
    {
      id: "cap-3",
      number: 3,
      name: "Threat Intelligence",
      blurb: "Threat intelligence and risk correlation.",
      features: ["Dark Web Monitoring", "Adversary Tracking", "Indicator Sharing"],
      price: 30,
      category: "Capability",
    },
    {
      id: "cap-19",
      number: 19,
      name: "Incident Response",
      blurb: "Incident detection and response.",
      features: ["Automated Triage", "Remote Remediation", "Playbook Execution"],
      price: 35,
      category: "Capability",
    },
    {
      id: "cap-7",
      number: 7,
      name: "Payload Protection",
      blurb: "Attachment and URL protection.",
      features: ["Deep Content Inspection", "Static Analysis", "Dynamic Scanning"],
      price: 10,
      category: "Capability",
    },
    {
      id: "cap-16",
      number: 16,
      name: "Endpoint Hardening",
      blurb: "Endpoint hardening and policy enforcement.",
      features: ["OS Hardening", "Vulnerability Assessment", "Patch Verification"],
      price: 15,
      category: "Capability",
    },
    {
      id: "cap-8",
      number: 8,
      name: "Compliance Readiness",
      blurb: "Compliance, retention, and audit readiness.",
      features: ["Audit Logs", "Data Retention Policies", "Regulatory Mapping"],
      price: 20,
      category: "Capability",
    },
    {
      id: "cap-11",
      number: 11,
      name: "Security Monitoring",
      blurb: "Security monitoring and alerting.",
      features: ["24/7 Monitoring", "High Fidelity Alerts", "Custom Rule Creation"],
      price: 12,
      category: "Capability",
    },
    {
      id: "cap-14",
      number: 14,
      name: "Awareness Training",
      blurb: "User security awareness and behavior training.",
      features: ["Interactive Modules", "Phishing Simulation", "Reporting Dashboard"],
      price: 5,
      category: "Capability",
    },
    {
      id: "cap-9",
      number: 9,
      name: "Operational Resilience",
      blurb: "Backup, recovery, and operational resilience.",
      features: ["Immutable Backup", "Rapid Recovery", "Disaster Testing"],
      price: 25,
      category: "Capability",
    },
    {
      id: "cap-12",
      number: 12,
      name: "Vulnerability Management",
      blurb: "Continuous vulnerability and risk management.",
      features: ["Prioritized Risk", "Asset Discovery", "Remediation Tracking"],
      price: 18,
      category: "Capability",
    },
    {
      id: "cap-5",
      number: 5,
      name: "Posture Visibility",
      blurb: "Overall security posture visibility and reporting.",
      features: ["Executive Dashboards", "Security Score", "Benchmarking"],
      price: 10,
      category: "Capability",
    },
  ],
  email: [
    {
      id: "email-gateway",
      name: "Email Security Cloud Gateway",
      price: 12,
      blurb:
        "100% cloud-native secure email gateway for Microsoft 365 and Google Workspace with AI-powered threat detection.",
      features: [
        "AI Threat Detection",
        "URL Scanning",
        "Quishing Protection",
        "Brand Impersonation Detection",
      ],
      category: "Email Security",
    },
    {
      id: "email-advanced",
      name: "Advanced Email Security",
      price: 18,
      blurb: "Multi-layered protection against sophisticated attacks including BEC and ransomware.",
      features: [
        "BEC Protection",
        "Spear-phishing Blocking",
        "Contextual Email Banners",
        "Malware Protection",
      ],
      category: "Email Security",
    },
    {
      id: "email-dmarc",
      name: "DMARC Analyzer",
      price: 8,
      blurb: "Comprehensive email authentication and domain protection to prevent spoofing.",
      features: [
        "Domain Spoofing Prevention",
        "Deliverability Improvement",
        "DMARC Policy Management",
      ],
      category: "Email Security",
    },
    {
      id: "email-engage",
      name: "Engage Awareness",
      price: 5,
      blurb: "Security awareness training focused on behavior-focused continuous intervention.",
      features: [
        "Phishing Simulations",
        "Risk Scoring",
        "Behavioral Analytics",
        "Educational Content",
      ],
      category: "Email Security",
    },
    {
      id: "email-collab",
      name: "Collaboration Security",
      price: 10,
      blurb: "Extends protection to Microsoft Teams, Slack, and SharePoint against data leaks and threats.",
      features: ["Teams/Slack Protection", "DLP for Collaboration", "Compliance Monitoring"],
      category: "Email Security",
    },
  ],
  endpoint: [
    {
      id: "ep-prevent",
      name: "Falcon Prevent (NGAV)",
      price: 8,
      blurb: "Next-gen antivirus with AI-powered detection; stops malware, ransomware, and zero-day threats.",
      features: ["AI-Powered Detection", "Ransomware Prevention", "Zero-Day Protection", "Lightweight Agent"],
      category: "Endpoint Security",
    },
    {
      id: "ep-insight",
      name: "Falcon Insight (EDR/XDR)",
      price: 15,
      blurb: "Endpoint detection & response with real-time visibility, automated detection, and forensics.",
      features: ["Real-Time Visibility", "Automated Detection", "Incident Investigation", "Forensic Analysis"],
      category: "Endpoint Security",
    },
    {
      id: "ep-overwatch",
      name: "Falcon OverWatch",
      price: 12,
      blurb: "Elite 24/7 managed threat hunting by experts to proactively stop breaches.",
      features: ["24/7 Threat Hunting", "Proactive Detection", "Expert Analysis", "Breach Prevention"],
      category: "Endpoint Security",
    },
    {
      id: "ep-identity",
      name: "Falcon Identity Protection",
      price: 10,
      blurb: "Real-time identity threat detection and MFA enforcement for compromised credentials.",
      features: [
        "Identity Threat Detection",
        "MFA Enforcement",
        "Credential Protection",
        "Zero-Trust Verification",
      ],
      category: "Endpoint Security",
    },
    {
      id: "ep-complete",
      name: "Falcon Complete MDR",
      price: 25,
      blurb: "Fully managed 24/7 expert-led monitoring and response for total endpoint protection.",
      features: ["Managed Monitoring", "Expert Response", "Remediation Services", "$1M Breach Warranty"],
      category: "Endpoint Security",
    },
  ],
  plans: [
    {
      id: "plan-starter",
      name: "Starter",
      price: 10,
      blurb: "Perfect for startups and small teams",
      features: ["Basic Email Security", "Endpoint Antivirus", "Standard Support"],
      category: "Plan",
      highlighted: false,
    },
    {
      id: "plan-business",
      name: "Business",
      price: 18,
      blurb: "Advanced protection for growing companies",
      features: [
        "Advanced AI Phishing Block",
        "Full EDR Suite",
        "Priority Support",
        "Vulnerability Scanning",
      ],
      category: "Plan",
      highlighted: true,
    },
    {
      id: "plan-enterprise",
      name: "Enterprise",
      price: 35,
      blurb: "Premier security for large-scale operations",
      features: [
        "CrowdStrike + Mimecast Integration",
        "24/7 Managed Response",
        "Custom Security Playbooks",
        "Global Threat Intel",
      ],
      category: "Plan",
      highlighted: false,
    },
  ],
};

window.TW24_findProduct = function (id) {
  const p = window.TW24_PRODUCTS;
  return (
    [...p.capabilities, ...p.email, ...p.endpoint, ...p.plans].find((x) => x.id === id) || null
  );
};
